name: marvel-heroes
services:
  front:
    image: node:lts-alpine
    user: node
    working_dir: /home/node/app
    command: npm run start:dev
    expose:
      - '${VITE_PORT}'
    ports:
      - '${VITE_PORT}:${VITE_PORT}'
      - 9228:9229
    volumes:
      - ./:/home/node/app
    env_file:
      - .env

